apiVersion: apps/v1
kind: Deployment
metadata:
  name: t3demo
spec:
  selector:
    matchLabels:
      app: t3demo
  template:
    metadata:
      labels:
        app: t3demo
    spec:
      containers:
      - name: t3demo
        image: t3demo:latest
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: t3demo-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: t3demo-secret
              key: password
