apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-job
            image: my-image
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
