apiVersion: v1
kind: Pod
metadata:
  name: t3demo
spec:
  containers:
  - name: t3demo
    image: gcr.io/k8-3s-388721/t3demo:v1.0.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-data
      mountPath: /var/app/t3demo/data
  volumes:
  - name: app-data
    hostPath:
      path: /app/data
