apiVersion: v1
kind: Pod
metadata:
  name: t3demo
spec:
  containers:
  - name: t3demo
    image: gcr.io/k8-3s-388721/t3demo:v1.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
